app = "mn-proof-choreo-kits"
primary_region = "lhr"

[build]
  image = "midnightntwrk/proof-server:latest"

[http_service]
  internal_port = 6300
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
